// Code generated by go generate; DO NOT EDIT.
// This file was generated by scripts/models/gen_nullable_types.go
package nullable


import (
	"bytes"
	"context"
	"encoding/json"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// Compile time validation that our types implement the expected interfaces
var (
	_ runtime.Validatable        = &Int8{}
	_ runtime.ContextValidatable = &Int8{}
	_ runtime.Validatable        = &Int8Slice{}
	_ runtime.ContextValidatable = &Int8Slice{}
)

// Int8 represents a int8 that may be null
type Int8 struct {
	Valid   bool // Valid is true if value is not null and valid int8
	Value   int8
}

// NewInt8 creates a new Int8 object
func NewInt8(val *int8) Int8 {
    if val == nil {
        return Int8{}
    }
    return Int8{
        Valid: true,
        Value: *val,
    }
}

// Returns nil if not present or valid. Otherwise it will
// return a pointer to the value.
func (i *Int8) Get() *int8 {
    if !i.Valid {
        return nil
    }
    return &i.Value
}

// Set sets the value and valid flag to true
func (i *Int8) Set(val int8) {
    i.Valid = true
    i.Value = val
}

func (i *Int8) UnmarshalJSON(data []byte) error {
    if bytes.Equal(data, null) || bytes.Equal(data, empty) || bytes.Equal(data, []byte("")) {
        return nil
    }
    if err := json.Unmarshal(data, &i.Value); err != nil {
        return err
    }
    i.Valid = true
    return nil
}

// Validate implements runtime.Validateable interface from github.com/go-openapi/runtime
func (i *Int8) Validate(formats strfmt.Registry) error {
    return nil 
}

// ContextValidate implements runtime.ContextValidatable from github.com/go-openapi/runtime
func (i *Int8) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// Int8Slice represents a []int8 that may be null
type Int8Slice struct {
	Valid   bool // Valid is true if value is not null
	Value   []int8
}


// NewInt8Slice creates a new Int8Slice object
func NewInt8Slice(val []int8) Int8Slice {
    if val == nil {
        return Int8Slice{}
    }
    return Int8Slice{
        Valid: true,
        Value: val,
    }
}

// UnmarshalJSON implements json.Marshaler interface.
func (i *Int8Slice) UnmarshalJSON(data []byte) error {
    if bytes.Equal(data, null) {
        i.Valid = false
        return nil
    }
    if err := json.Unmarshal(data, &i.Value); err != nil {
        return err
    }
    i.Valid = true
    return nil
}

// Returns nil if not present or valid. Otherwise it will
// return a pointer to the value.
func (i *Int8Slice) Get() *[]int8 {
    if !i.Valid {
        return nil
    }
    return &i.Value
}

// Validate implements runtime.Validateable interface from github.com/go-openapi/runtime
func (i *Int8Slice) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate implements runtime.ContextValidatable from github.com/go-openapi/runtime
func (i *Int8Slice) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}